title: "Maximiliano Dalla Porta"
email: "gigamax13@gmail.com"
description: "Senior Software Engineer (ğšƒğš¢ğš™ğšğš‚ğšŒğš›ğš’ğš™ğš, ğšğšğšŠğšŒğš, ğ™½ğš˜ğšğš, ğ™°ğš†ğš‚)"
baseurl: "" # leave empty for GitHub Pages
url: "https://GigaMax13.github.io"
sass:
  sass_dir: _sass
  style: compressed
